### ISSUE TITLE
Does not work on 1.21

### ISSUE THREAD

**Issue by aquahonoredhi** [pog5/CommandDumper#1]
The mod does not work on 1.21, despite it being listed as a 1.21.x mod

**Comment by pog5** [comment]
hi 👋 can I have your fabric version and a crash log?

**Comment by aquahonoredhi** [comment]
fabric loader is most recent version. This should not need a crash report as the loader simply says the mod is incompatible with 1.21.0

**Comment by pog5** [comment]
I've updated the source, you can build it right now or wait for the update to get pushed to modrinth

**Comment by aquahonoredhi** [comment]
The update does not appear to have been pushed to modrinth

**Comment by pog5** [comment]
> The update does not appear to have been pushed to modrinth

fixed, my bad

**Comment by aquahonoredhi** [comment]
mate, the issue was it didnt work with **1.21.0**, **Not 1.21.1**. It still does not work.

**Comment by Qwertylex** [comment]
could we have an update for 1.21.10 ?

**Comment by pog5** [comment]
> mate, the issue was it didnt work with **1.21.0**, **Not 1.21.1**. It still does not work.
1.21.1 is the same version as 1.21.0, just with some important bugfixes.

> could we have an update for 1.21.10 ?
planned, thank you
